# ==============================================================================
# Goldilocks Production Environment Overrides
# LIGHTWEIGHT - Minimal resources, maximum performance
# HIGH COMPATIBILITY - Production-ready configurations
# MODERNIZE - Latest security and monitoring practices
# ==============================================================================

services:
  goldilocks-backend:
    # Production environment configurations
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONOPTIMIZE: 2
      LOG_LEVEL: INFO
      LOG_FORMAT: json
      ENABLE_METRICS: true
      ENABLE_PROFILER: false
      ENABLE_QUERY_PROFILER: false

    # Production resource limits (optimized for efficiency)
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '1.0'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    # Enhanced production health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  goldilocks-db:
    # Production database configurations
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: goldilocks
      MARIADB_USER: goldilocks_app
      MARIADB_PASSWORD: ${MARIADB_APP_PASSWORD}

    # Production MySQL optimizations
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=512M
      - --innodb-log-file-size=128M
      - --innodb-flush-log-at-trx-commit=1
      - --innodb-flush-method=O_DIRECT
      - --max-connections=200
      - --query-cache-size=64M
      - --query-cache-type=1
      - --slow-query-log=1
      - --long-query-time=2

    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.5'
        reservations:
          memory: 512M
          cpus: '0.75'

    # Production health check
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Remove Adminer in production for security
  goldilocks-adminer:
    profiles:
      - debug  # Only available when explicitly requested

# Production-specific volumes
volumes:
  goldilocks-prod-logs:
    name: goldilocks_prod_logs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GOLDILOCKS_LOGS_PATH:-/opt/goldilocks/logs}/prod

  goldilocks-prod-uploads:
    name: goldilocks_prod_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${GOLDILOCKS_DATA_PATH:-/opt/goldilocks/data}/uploads
