services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: goldilocks-flask:latest
    container_name: goldilocks-web
    privileged: true
    network_mode: host
    init: true
    ports:
      - "9000:9000"
    environment:
      - FLASK_APP=app.py
    volumes:
      - ./:/app
      - pip-cache:/root/.cache/pip
    ulimits:
      nofile: 1048576
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    command:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:9000",
        "--workers",
        "0",
        "--threads",
        "2",
        "--access-logfile",
        "-",
        "--error-logfile",
        "-",
        "app:app",
      ]
    restart: unless-stopped

volumes:
  pip-cache:
