# filepath: /app/pyproject.toml
[tool.black]
line-length = 79
target-version = ["py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 79
known_first_party = ["goldilocks", "app"]
src_paths = ["src", "."]

[tool.flake8]
max-line-length = 79
extend-ignore = ["E203", "W503"]

[tool.pytest.ini_options]
testpaths = ["src/tests"]
addopts = "-q --cov=goldilocks --cov-report=term-missing"
pythonpath = ["src", "."]

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = false
warn_return_any = false
check_untyped_defs = true
no_implicit_optional = true
pretty = true
explicit_package_bases = true
mypy_path = ["src", "."]
files = ["src/goldilocks/app.py", "src/goldilocks/api", "src/goldilocks/core", "src/goldilocks/models", "src/goldilocks/services", "src/goldilocks/utils"]
ignore_missing_imports = true
exclude = ["src/tests", "tests"]

[[tool.mypy.overrides]]
module = [
    "flask_wtf.*",
    "wtforms.*",
    "flask_login.*",
    "flask_sqlalchemy.*",
]
ignore_missing_imports = true
