[tool.black]
line-length = 100
target-version = ["py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["app"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q --cov=app --cov-report=term-missing"

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
check_untyped_defs = true
no_implicit_optional = true
pretty = true

[tool.flake8]
max-line-length = 100
extend-select = ["B","C4"]
ignore = ["W503"]
per-file-ignores = {}