# Goldilocks Ultra-Performance Docker Compose Configuration
# Modular, Maintainable, and Scalable Microservice Architecture
# Adheres to: MODERNIZE, DRY, STRUCTURED, MONOLITHIC, STANDARDIZATION, LOW FOOTPRINT

# MODERNIZE: Latest Docker Compose specification
version: "3.9"

# STRUCTURED: Environment-specific configurations available in compose/overrides/
# Usage Examples:
#   Development: docker-compose -f docker-compose.yml -f compose/overrides/development.yml up -d
#   Production:  docker-compose -f docker-compose.yml -f compose/overrides/production.yml up -d
#   Testing:     docker-compose -f docker-compose.yml -f compose/overrides/testing.yml up -d
#   CI/CD:       docker-compose -f docker-compose.yml -f compose/overrides/ci-cd.yml run --rm goldilocks-app
#   Edge:        docker-compose -f docker-compose.yml -f compose/overrides/edge.yml up -d

# STRUCTURED: Include service definitions following SRP
include:
  # Core application services
  - compose/services/database.yml
  - compose/services/backend.yml
  - compose/services/frontend.yml
  - compose/services/adminer.yml

# MODERNIZE: Global service configurations
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"
    compress: "true"

x-restart-policy: &restart-policy
  restart: unless-stopped

# DRY: Common service extensions
x-common-labels: &common-labels
  com.goldilocks.project: "goldilocks"
  com.goldilocks.version: "${APP_VERSION:-1.0.0}"
  com.goldilocks.environment: "${ENVIRONMENT:-development}"

# HIGH COMPATIBILITY: Multi-environment service overrides
services:
  # Apply common configurations to all services
  goldilocks-db:
    <<: *restart-policy
    logging: *default-logging
    labels: *common-labels

  goldilocks-backend:
    <<: *restart-policy
    logging: *default-logging
    labels: *common-labels

  goldilocks-frontend:
    <<: *restart-policy
    logging: *default-logging
    labels: *common-labels

  goldilocks-adminer:
    <<: *restart-policy
    logging: *default-logging
    labels: *common-labels

# STRUCTURED: Global volume definitions
volumes:
  # Persistent application data
  goldilocks-app-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/app
    labels: *common-labels

# LOW FOOTPRINT: Optimized network configuration
networks:
  goldilocks-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: goldilocks0
      com.docker.network.bridge.enable_icc: "true"
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      config:
        - subnet: 172.20.0.0/24
          gateway: 172.20.0.1
    labels: *common-labels

# STRUCTURED: Environment-specific configurations
configs:
  app-config:
    file: ${CONFIG_PATH:-./config}/app.conf

  nginx-config:
    file: ${CONFIG_PATH:-./config}/nginx.conf

# SECURITY: Secrets management
secrets:
  db-password:
    external: true
    name: goldilocks_db_password

  app-secret-key:
    external: true
    name: goldilocks_app_secret
