# Goldilocks Ultra-Performance Docker Compose Configuration
# Modular, Maintainable, and Scalable Microservice Architecture
# Adheres to: MODERNIZE, DRY, STRUCTURED, MONOLITHIC, STANDARDIZATION, LOW FOOTPRINT

# STRUCTURED: Environment-specific configurations available in compose/overrides/
# Usage Examples:
#   Development: docker-compose -f docker-compose.yml -f compose/overrides/development.yml up -d
#   Production:  docker-compose -f docker-compose.yml -f compose/overrides/production.yml up -d
#   Testing:     docker-compose -f docker-compose.yml -f compose/overrides/testing.yml up -d
#   CI/CD:       docker-compose -f docker-compose.yml -f compose/overrides/ci-cd.yml run --rm goldilocks-app
#   Edge:        docker-compose -f docker-compose.yml -f compose/overrides/edge.yml up -d

# STRUCTURED: Include service definitions following SRP
include:
  # Shared infrastructure components
  - compose/shared/networks.yml
  - compose/shared/volumes.yml
  - compose/shared/secrets.yml

  # Core application services
  - compose/services/database.yml
  - compose/services/backend.yml
  - compose/services/frontend.yml
  - compose/services/adminer.yml

  # Development tools services (SEPARATION OF CONCERNS)
  - compose/services/extensions.yml

# MODERNIZE: Global service configurations
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"
    compress: "true"

x-restart-policy: &restart-policy
  restart: unless-stopped

# DRY: Common service extensions
x-common-labels: &common-labels
  com.goldilocks.project: "goldilocks"
  com.goldilocks.version: "${APP_VERSION:-1.0.0}"
  com.goldilocks.environment: "${ENVIRONMENT:-development}"

# STRUCTURED: Global volume definitions - Additional application volumes
volumes:
  # Additional application data volumes
  goldilocks-app-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH:-./data}/app
    labels: *common-labels

# STRUCTURED: Environment-specific configurations
configs:
  app-config:
    file: ${CONFIG_PATH:-./config}/app.conf

  nginx-config:
    file: ${CONFIG_PATH:-./config}/nginx.conf

# SECURITY: Secrets management
secrets:
  db-password:
    external: true
    name: goldilocks_db_password

  app-secret-key:
    external: true
    name: goldilocks_app_secret
