services:
  # Frontend tooling service - separate Node.js container
  goldilocks-frontend:
    image: node:22-alpine
    container_name: goldilocks-frontend
    restart: unless-stopped
    volumes:
      - ../..:/workspace:cached
      - goldilocks-node-modules:/workspace/node_modules
      - npm-cache:/home/node/.npm
    working_dir: /workspace
    command: ["tail", "-f", "/dev/null"] # Keep container running
    networks:
      - goldilocks-network
    profiles: ["dev", "frontend"]

  # MariaDB database service - optimized for edge computing
  goldilocks-db:
    image: mariadb:11.2
    container_name: goldilocks-db
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=goldilocks_root_2024
      - MARIADB_DATABASE=goldilocks
      - MARIADB_USER=goldilocks_user
      - MARIADB_PASSWORD=goldilocks_pass_2024
      # Edge computing optimizations
      - MARIADB_INIT_CONNECT='SET sql_mode="STRICT_TRANS_TABLES,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"'
    volumes:
      - goldilocks-db-data:/var/lib/mysql
      - ./mariadb-init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
    networks:
      - goldilocks-network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --innodb-log-file-size=64M
      --innodb-flush-log-at-trx-commit=2
      --innodb-flush-method=O_DIRECT
      --query-cache-type=1
      --query-cache-size=32M
      --max-connections=100
      --table-open-cache=512
      --thread-cache-size=16
      --key-buffer-size=32M
      --tmp-table-size=32M
      --max-heap-table-size=32M
      --skip-name-resolve
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    profiles: ["dev", "prod"]

  # Adminer database management interface - lightweight
  goldilocks-adminer:
    image: adminer:4.8.1-standalone
    container_name: goldilocks-adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - goldilocks-network
    environment:
      - ADMINER_DEFAULT_SERVER=goldilocks-db
      - ADMINER_DESIGN=pappu687
    depends_on:
      goldilocks-db:
        condition: service_healthy
    profiles: ["dev"]

  # Development service with tools and hot reload
  goldilocks-dev:
    build:
      context: ../..
      dockerfile: infrastructure/docker/dockerfiles/Dockerfile.multi-stage
      target: devcontainer
      cache_from:
        - goldilocks:devcontainer
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: goldilocks-dev
    restart: unless-stopped
    command: flask run --host 0.0.0.0 --port 9000
    volumes:
      - ../..:/workspaces/Goldilocks:cached
      - goldilocks-venv:/opt/venv
      - goldilocks-bytecode-cache:/workspaces/Goldilocks/__pycache__
      - pip-cache:/home/app/.cache/pip
      - pre-commit-cache:/home/app/.cache/pre-commit
      - mypy-cache:/home/app/.mypy_cache
      - pytest-cache:/home/app/.cache/pytest
      - ruff-cache:/home/app/.cache/ruff
      - buildx-cache:/tmp/.buildx-cache
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/workspaces/Goldilocks/src
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=0
      - DOCKER_BUILDKIT=1
      - BUILDKIT_PROGRESS=plain
      # Database connection
      - DATABASE_URL=mysql+pymysql://goldilocks_user:goldilocks_pass_2024@goldilocks-db:3306/goldilocks
      - DB_HOST=goldilocks-db
      - DB_PORT=3306
      - DB_NAME=goldilocks
      - DB_USER=goldilocks_user
      - DB_PASSWORD=goldilocks_pass_2024
    ports:
      - "9000:9000"
    working_dir: /workspaces/Goldilocks
    networks:
      - goldilocks-network
    depends_on:
      goldilocks-db:
        condition: service_healthy
    profiles: ["dev"]

  # Production service with minimal footprint
  goldilocks-prod:
    build:
      context: ../..
      dockerfile: infrastructure/docker/dockerfiles/Dockerfile.multi-stage
      target: runtime
      cache_from:
        - goldilocks:runtime
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: goldilocks-prod
    restart: unless-stopped
    volumes:
      - goldilocks-data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - WORKERS=2
      - TIMEOUT=30
    ports:
      - "9000:9000"
    networks:
      - goldilocks-network
    profiles: ["prod"]

  # Build-only service for CI/CD and caching
  goldilocks-builder:
    build:
      context: ../..
      dockerfile: infrastructure/docker/dockerfiles/Dockerfile.multi-stage
      target: builder
      cache_from:
        - goldilocks:builder
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: goldilocks-builder
    volumes:
      - goldilocks-build-cache:/app/precompiled
    profiles: ["build"]

volumes:
  # Database data volume - persistent MariaDB storage
  goldilocks-db-data:
    driver: local

  # Virtual environment cache - persistent across rebuilds
  goldilocks-venv:
    driver: local

  # Node modules cache
  goldilocks-node-modules:
    driver: local

  # Python bytecode cache
  goldilocks-bytecode-cache:
    driver: local

  # Build cache for instant rebuilds
  goldilocks-build-cache:
    driver: local

  # Application data
  goldilocks-data:
    driver: local

  # Package manager caches
  pip-cache:
    driver: local

  npm-cache:
    driver: local

  # Development tool caches
  pre-commit-cache:
    driver: local

  mypy-cache:
    driver: local

  pytest-cache:
    driver: local

  ruff-cache:
    driver: local

  # BuildKit cache for multi-stage builds
  buildx-cache:
    driver: local

networks:
  goldilocks-network:
    driver: bridge
