services:
  # Development service with tools and hot reload
  goldilocks-dev:
    image: goldilocks:devcontainer
    container_name: goldilocks-dev
    restart: unless-stopped
    command: flask run --host 0.0.0.0 --port 9000
    volumes:
      - ../..:/workspaces/Goldilocks:cached
      - goldilocks-venv:/opt/venv
      - goldilocks-node-modules:/workspaces/Goldilocks/node_modules
      - goldilocks-bytecode:/workspaces/Goldilocks/__pycache__
      - pip-cache:/home/app/.cache/pip
      - npm-cache:/home/app/.npm
    environment:
      - FLASK_APP=src/goldilocks/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONPATH=/workspaces/Goldilocks/src
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=0
    ports:
      - "9000:9000"
    working_dir: /workspaces/Goldilocks
    networks:
      - goldilocks-network
    profiles: ["dev"]

  # Production service with minimal footprint
  goldilocks-prod:
    image: goldilocks-flask:latest
    container_name: goldilocks-prod
    restart: unless-stopped
    volumes:
      - goldilocks-data:/app/data
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=0
      - WORKERS=2
      - TIMEOUT=30
    ports:
      - "9000:9000"
    networks:
      - goldilocks-network
    profiles: ["prod"]

  # Build-only service for CI/CD and caching
  goldilocks-builder:
    build:
      context: ../..
      dockerfile: infrastructure/docker/build.Dockerfile
      target: builder
      cache_from:
        - goldilocks:builder
      args:
        BUILDKIT_INLINE_CACHE: 1
    container_name: goldilocks-builder
    volumes:
      - goldilocks-build-cache:/app/precompiled
    profiles: ["build"]

volumes:
  goldilocks-venv:
  goldilocks-node-modules:
  goldilocks-bytecode:
  goldilocks-build-cache:
  goldilocks-data:
  pip-cache:
  npm-cache:

networks:
  goldilocks-network:
    driver: bridge
