# filepath: /app/pyproject.toml
[tool.black]
line-length = 100
target-version = ["py313"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 100
known_first_party = ["goldilocks", "app"]

[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]

[tool.pytest.ini_options]
testpaths = ["src/goldilocks/tests"]
addopts = "-q --cov=goldilocks --cov-report=term-missing"

[tool.mypy]
python_version = "3.13"
warn_unused_configs = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
check_untyped_defs = true
no_implicit_optional = true
pretty = true
explicit_package_bases = true
mypy_path = ["src"]
files = ["src"]
