name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"
          cache-dependency-path: requirements.txt
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run pytest with coverage
        run: pytest -q --cov=app --cov-report=xml --cov-report=term-missing
      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: ignore
      - name: Type check (mypy)
        run: mypy .
      - name: Pre-commit checks
        run: |
          pre-commit install-hooks
          pre-commit run --all-files
