# VS Code Extensions Service - Dedicated Development Tools Support
# Adheres to: SEPARATION OF CONCERNS, NO CROSS-CUTTING, STRUCTURED, DRY

services:
  goldilocks-extensions:
    build:
      context: ${DOCKER_CONTEXT_PATH:-../../../..}

    container_name: goldilocks-extensions
    restart: "no"

    # LIGHTWEIGHT: Minimal resources for extensions service
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

    # SEPARATION OF CONCERNS: Extensions and MCP servers provisioning command
    command: >
      sh -c "
        echo 'Provisioning GitHub Copilot extensions...' &&
        mkdir -p /root/.vscode-server-insiders/extensions &&
        mkdir -p /extensions-cache &&

        # Install VS Code Server CLI
        curl -L https://update.code.visualstudio.com/latest/server-linux-x64/insider -o /tmp/vscode-server-linux-x64.tar.gz &&
        mkdir -p /tmp/vscode-server &&
        tar -xzf /tmp/vscode-server-linux-x64.tar.gz -C /tmp/vscode-server --strip-components=1 &&

        # Install GitHub Copilot extensions
        /tmp/vscode-server/bin/code-server-insiders --install-extension github.copilot --extensions-dir /root/.vscode-server-insiders/extensions --force &&
        /tmp/vscode-server/bin/code-server-insiders --install-extension github.copilot-chat --extensions-dir /root/.vscode-server-insiders/extensions --force &&
        /tmp/vscode-server/bin/code-server-insiders --install-extension github.vscode-pull-request-github --extensions-dir /root/.vscode-server-insiders/extensions --force &&

        # Copy extensions to shared volume for persistence
        cp -r /root/.vscode-server-insiders/extensions/* /extensions-cache/ &&

        # Validate extensions installation
        echo 'Validating extensions installation...' &&
        ls -la /root/.vscode-server-insiders/extensions/ &&
        ls -la /extensions-cache/ &&

        # Run provision script for MCP servers
        /bin/bash /infrastructure/docker/scripts/provision-copilot-extensions.sh &&

        # Keep container running
        echo 'Extensions provisioning completed successfully!' &&
        tail -f /dev/null
      "

    # STRUCTURED: Extensions-specific volumes only
    volumes:
      # VS Code Server extensions and data persistence (dedicated)
      - goldilocks-vscode-server-extensions:/extensions-cache
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_CONTEXT_PATH:-../../../..}/infrastructure:/infrastructure

    # STRUCTURED: Extensions-specific environment
    environment:
      EXTENSIONS_PATH: /root/.vscode-server-insiders/extensions
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      VSCODE_AGENT_FOLDER: /root/.vscode-server-insiders
